<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DateTime;
use Illuminate\Support\Facades\DB;

class SanPhamTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $list = [];
        $date = new DateTime();
        $dsSanPham = [
            ['Thùng sữa vinamilk có đường 220ml', '3', '4', 'thung-sua-tuoi-co-duong-vinamilk-100-sua-tuoi-180ml_300x300.jpg', 'Sữa (94,6%), đường tinh luyện (2,8%), dầu thực vật, chất ổn định, hương liệu tổng hợp dùng cho thực phẩm, vitamin (A, D3)...', '', '220ml', 'nơi thoáng mát', 'Trẻ từ 1 tuổi trở lên', '', '', '6 tháng', 1],
            ['Thùng sữa tươi socola Vinamilk 100% Sữa Tươi 180ml', '3', '4', 'thung-sua-dinh-duong-socola-vinamilk-adm-gold-180ml_300x300.jpg', 'Sữa (94,6%), đường tinh luyện (2,8%), dầu thực vật, chất ổn định, hương liệu tổng hợp dùng cho thực phẩm, vitamin (A, D3)...', '', '180ml', 'nơi thoáng mát', 'Trẻ từ 1 tuổi trở lên', '', '', '6 tháng', 1],
            ['Thùng sữa vinamilk ít đường 220ml', '3', '4', 'thung-sua-dinh-duong-it-duong-vinamilk-220ml_300x300.jpg', 'Sữa (94,6%), đường tinh luyện (2,8%), dầu thực vật, chất ổn định, hương liệu tổng hợp dùng cho thực phẩm, vitamin (A, D3)...', '', '220ml', 'nơi thoáng mát', 'Trẻ từ 1 tuổi trở lên', '', '', '6 tháng', 1],
            ['Thùng sữa vinamilk không đường 220ml', '3', '4', 'thung-sua-tuoi-tach-beo-khong-duong-vinamilk-100-sua-tuoi-180ml_300x300.jpg', 'Sữa (94,6%), đường tinh luyện (2,8%), dầu thực vật, chất ổn định, hương liệu tổng hợp dùng cho thực phẩm, vitamin (A, D3)...', '', '220ml', 'nơi thoáng mát', 'Trẻ từ 1 tuổi trở lên', '', '', '6 tháng', 1],
            ['sữa vinamilk có đường 220ml', '3', '4', 'sua-dinh-duong-co-duong-vinamilk-happy-star-bich-220ml_300x300.jpg', 'Sữa (94,6%), đường tinh luyện (2,8%), dầu thực vật, chất ổn định, hương liệu tổng hợp dùng cho thực phẩm, vitamin (A, D3)...', '', '220ml', 'nơi thoáng mát', 'Trẻ từ 1 tuổi trở lên', '', '', '6 tháng', 1],
            ['Lốc sữa TH TrueMilk có đường 220ml', '3', '5', 'loc-sua-tuoi-tiet-trung-co-duong-th-true-milk-180ml_300x300.jpg', 'Sữa hoàn toàn từ sữa bò tươi (96%), đường tinh luyện, chất ổn định,...', '', '220ml', 'nơi thoáng mát', 'Trẻ từ 1 tuổi trở lên', '', '', '6 tháng', 1],
            ['Thùng sữa TH TrueMilk có đường 220ml', '3', '5', 'thung-sua-tuoi-tiet-trung-co-duong-th-true-milk-110ml_300x300.jpg', 'Sữa hoàn toàn từ sữa bò tươi (96%), đường tinh luyện, chất ổn định,...', '', '220ml', 'nơi thoáng mát', 'Trẻ từ 1 tuổi trở lên', '', '', '6 tháng', 1],
            ['Thùng sữa TH TrueMilk ít đường 220ml', '3', '5', 'thung-sua-tuoi-tiet-trung-it-duong-th-true-milk-180ml_300x300.jpg', 'Sữa hoàn toàn từ sữa bò tươi (96%), đường tinh luyện, chất ổn định,...', '', '220ml', 'nơi thoáng mát', 'Trẻ từ 1 tuổi trở lên', '', '', '6 tháng', 1],
            ['Lốc sữa dinh dưỡng hương dâu Vinamilk ADM Gold 180ml', '3', '4', 'thung-sua-dinh-duong-huong-dau-vinamilk-adm-gold-180ml_300x300.jpg', 'Sữa (93 %) (nước, sữa bột, chất béo sữa), đường tinh luyện, dầu thực vật, chất ổn định (471, 460(i), 407, 466), hương liệu tổng hợp dùng cho thực phẩm, màu tự nhiên (120), vitarmin (PP, D3, A, biotin, B1, B6, calci-D pantothenat, K1, acid folic, B12), khoáng chất (kẽm sulfat natioleic, kali iodid), lecithin', '', '180ml', 'nơi thoáng mát', 'Trẻ từ 1 tuổi trở lên', '', '', '6 tháng', 1],
            ['Lốc sữa đậu nành óc chó Vinamilk 180ml', '3', '4', 'loc-sua-dau-nanh-oc-cho-vinamilk-180ml_300x300.jpg', 'Dịch trích từ đậu nành hạt, nước, đường, dầu thực vật,...', '', '180ml', 'nơi thoáng mát', 'Trẻ từ 4 tuổi trở lên', '', '', '6 tháng', 1],
            ['Lốc sữa chua uống hương việt quất TH True Yogurt 180ml', '3', '5', 'loc-sua-chua-uong-huong-viet-quat-th-true-yogurt-180ml_300x300.jpg', 'Dịch trích từ đậu nành hạt, nước, đường, dầu thực vật,...', '', '180ml', 'nơi thoáng mát', 'Trẻ từ 1 tuổi trở lên', '', '', '3 tháng', 1],
            ['Thùng sữa chua uống hương việt quất TH True Yogurt 180ml', '3', '4', 'thung-sua-chua-uong-huong-viet-quat-th-true-yogurt-180ml_300x300.jpg', 'Dịch trích từ đậu nành hạt, nước, đường, dầu thực vật,...', '', '180ml', 'nơi thoáng mát', 'Trẻ từ 1 tuổi trở lên', '', '', '3 tháng', 1],
            ['Lốc sữa trái cây vị dâu Vinamilk Hero hộp 110ml', '3', '4', 'loc-sua-trai-cay-vi-dau-vinamilk-hero-hop-110ml_300x300.jpg', 'Nước, đường siro glucoze, sữa bột, nước táo ép cô đặc, nước dâu ép cô đặc, chất ổn định, chất béo sữa, chất điều chỉnh độ acid, hương dâu dùng cho thực phẩm,...', '', '110ml', 'nơi khô ráo, thoáng mát. Tránh tiếp xúc với ánh sáng mặt trời', 'Trẻ từ 1 tuổi trở lên', '', '', '6 tháng', 1],
            ['Thùng sữa trái cây vị dâu Vinamilk Hero hộp 110ml ', '3', '4', 'thung-sua-trai-cay-vi-dau-vinamilk-hero-hop-110ml_300x300.jpg', 'Nước, đường siro glucoze, sữa bột, nước táo ép cô đặc, nước dâu ép cô đặc, chất ổn định, chất béo sữa, chất điều chỉnh độ acid, hương dâu dùng cho thực phẩm,...', '', '110ml', 'nơi thoáng mát', 'Trẻ từ 1 tuổi trở lên', '', '', '6 tháng', 1],
            ["Snack khoai tây vị tảo biển nori Lay's gói 52g ", '3', '4', 'snack-khoai-tay-vi-tao-bien-nori-lays-goi-52g_300x300.jpg', '  Khoai tây, dầu cọ, bột gia vị tảo biển Nori 6% (đường, maltodextrin, muối, hương liệu giống tự nhiên, chất điều vị (E621, E631), nước tương, bột tỏi, bột hành, gia vị (ớt, gừng), chất chống đông vón E554, chất điều chỉnh độ axit E330, dầu đậu nành, màu tự nhiên E160c, chất tạo ngọt E951)', '', '52g', 'nơi thoáng mát', '', 'Không dành cho trẻ dưới 1 tuổi', '', '6 tháng', 1],
            ["Snack khoai tây vị tự nhiên Classic Lay's gói 52g ", '3', '4', 'snack-khoai-tay-vi-tu-nhien-classic-lays-goi-52g_300x300.jpg', 'Khoai tây, dầu cọ, bột gia vị tảo biển Nori 6% (đường, maltodextrin, muối, hương liệu giống tự nhiên, chất điều vị (E621, E631), nước tương, bột tỏi, bột hành, gia vị (ớt, gừng), chất chống đông vón E554, chất điều chỉnh độ axit E330, dầu đậu nành, màu tự nhiên E160c, chất tạo ngọt E951)', '', '52g', 'nơi thoáng mát', '', 'Không dành cho trẻ dưới 1 tuổi', '', '6 tháng', 1],
            ['Lốc nước ngọt Coca Cola 600ml', '1', '6', 'loc-nuoc-ngot-coca-cola-600m_300x300.jpg', 'Nước bão hòa CO2, đường HFCS, đường mía, màu thực phẩm, chất điều chỉnh độ acid, hương cola tự nhiên, caffeine.', 'Ngon hơn khi uống lạnh', '600ml', 'nơi thoáng mát', '', 'Không dành cho trẻ dưới 1 tuổi', '', '6 tháng', 1],
            ['Thùng nước ngọt Coca Cola 600ml', '1', '6', 'thung-nuoc-ngot-coca-cola-600ml_300x300.jpg', 'Nước bão hòa CO2, đường HFCS, đường mía, màu thực phẩm, chất điều chỉnh độ acid, hương cola tự nhiên, caffeine.', 'Ngon hơn khi uống lạnh', '600ml', 'nơi thoáng mát', '', 'Không dành cho trẻ dưới 1 tuổi', '', '6 tháng', 1],
            ['Nước ngọt Coca Cola 600ml', '1', '6', 'nuoc-ngot-coca-cola-600ml_300x300.jpg', 'Nước bão hòa CO2, đường HFCS, đường mía, màu thực phẩm, chất điều chỉnh độ acid, hương cola tự nhiên, caffeine.', 'Ngon hơn khi uống lạnh', '600ml', 'nơi thoáng mát', '', 'Không dành cho trẻ dưới 1 tuổi', '', '6 tháng', 1],
            ['Nước ngọt Pepsi không calo vị chanh 320ml', '1', '7', 'nuoc-ngot-pepsi-khong-calo-vi-chanh-320ml.jpg', ' Nước bão hoà CO2, chất điều chỉnh độ axit, màu tổng hợp, hỗn hợp hương chanh tự nhiên, chất tạo ngọt tổng hợp, chất bảo quản, caffeine', 'Ngon hơn khi uống lạnh', '320ml', 'nơi thoáng mát', '', 'Không dành cho trẻ dưới 1 tuổi', ' Sản phẩm có chứa phenylalanine, có thể không bị hợp với người bị phenylketonuria', '6 tháng', 1],
            ['Lốc nước ngọt Pepsi không calo vị chanh 320ml', '1', '7', 'loc-nuoc-ngot-pepsi-khong-calo-vi-chanh-320ml-300x300.jpg', ' Nước bão hoà CO2, chất điều chỉnh độ axit, màu tổng hợp, hỗn hợp hương chanh tự nhiên, chất tạo ngọt tổng hợp, chất bảo quản, caffeine', 'Ngon hơn khi uống lạnh', '320ml', 'nơi thoáng mát', '', 'Không dành cho trẻ dưới 1 tuổi', ' Sản phẩm có chứa phenylalanine, có thể không bị hợp với người bị phenylketonuria', '6 tháng', 1],
            ['Thùng nước ngọt Pepsi không calo vị chanh 320ml', '1', '7', 'thung-nuoc-ngot-pepsi-khong-calo-vi-chanh-320ml_300x300.jpg', ' Nước bão hoà CO2, chất điều chỉnh độ axit, màu tổng hợp, hỗn hợp hương chanh tự nhiên, chất tạo ngọt tổng hợp, chất bảo quản, caffeine', 'Ngon hơn khi uống lạnh', '320ml', 'nơi thoáng mát', '', 'Không dành cho trẻ dưới 1 tuổi', ' Sản phẩm có chứa phenylalanine, có thể không bị hợp với người bị phenylketonuria', '6 tháng', 1],
            ['Thùng nước ngọt Pepsi không calo 320ml', '1', '7', 'thung-nuoc-ngot-pepsi-khong-calo-320ml_300x300.jpg', ' Nước bão hoà CO2, chất điều chỉnh độ axit, màu tổng hợp, hỗn hợp hương chanh tự nhiên, chất tạo ngọt tổng hợp, chất bảo quản, caffeine', 'Ngon hơn khi uống lạnh', '320ml', 'nơi thoáng mát', '', 'Không dành cho trẻ dưới 1 tuổi', ' Sản phẩm có chứa phenylalanine, có thể không bị hợp với người bị phenylketonuria', '6 tháng', 1],

            ['Lốc nước ngọt Pepsi không calo 320ml', '1', '7', 'loc-nuoc-ngot-pepsi-khong-calo-320ml-300x300.jpg', ' Nước bão hoà CO2, chất điều chỉnh độ axit, màu tổng hợp, hỗn hợp hương chanh tự nhiên, chất tạo ngọt tổng hợp, chất bảo quản, caffeine', 'Ngon hơn khi uống lạnh', '320ml', 'nơi thoáng mát', '', 'Không dành cho trẻ dưới 1 tuổi', ' Sản phẩm có chứa phenylalanine, có thể không bị hợp với người bị phenylketonuria', '6 tháng', 1],
            ['Nước ngọt Pepsi không calo 320ml', '1', '7', 'nuoc-ngot-pepsi-khong-calo-330ml_300x300.jpg', ' Nước bão hoà CO2, chất điều chỉnh độ axit, màu tổng hợp, hỗn hợp hương chanh tự nhiên, chất tạo ngọt tổng hợp, chất bảo quản, caffeine', 'Ngon hơn khi uống lạnh', '320ml', 'nơi thoáng mát', '', 'Không dành cho trẻ dưới 1 tuổi', ' Sản phẩm có chứa phenylalanine, có thể không bị hợp với người bị phenylketonuria', '6 tháng', 1],
            ['Trà Atisô Lama hộp 50g', '1', '1', 'tra-atiso-lama-hop-50g_300x300.jpg', ' Atisô 95%, cỏ ngọt 5%', ' Cho túi trà vào tách nước sôi khoảng 150ml. Để từ 3 - 5 phút.Có thể thưởng thức nóng, lạnh hoặc pha với chanh, đường tùy khẩu vị.', '50g', 'nơi thoáng mát', '', 'Không dành cho trẻ dưới 1 tuổi', '', '6 tháng', 1],
            ['Cà phê sữa VinaCafé Gold Original 800g', '1', '1', 'ca-phe-sua-vinacafe-gold-original-800g_300x300.jpg', ' 100% từ hạt cà phê Robusta và Arabica chất lượng', ' UỐNG NÓNG dùng 1 gói pha với 70-75ml nước nóng. UỐNG LẠNH dùng 2 gói pha với 50-70ml nước nóng và thêm đá.', '800g ', 'nơi thoáng mát', '', 'Không dành cho trẻ dưới 1 tuổi', '', '6 tháng', 1],

            ['Thùng mì Hảo Hảo tôm chua cay 75g ', '4', '1', 'thung-mi-hao-hao-tom-chua-cay-75g_300x300.jpg', " VẮT MÌ - Bột mì (bổ sung vi chất (kẽm, sắt)), dầu thực vật (dầu cọ, chất chống oxy hoá (BHA (320), BHT (321))), tinh bột, muối, đường, nước mắm, chất điều vị (mononatri glutamat (621)), chất ổn định (pentanatri triphosphat (451(i), kali carbonat (501(i))), chất điều chỉnh độ acid (natri carbonat (500(i))), bột nghệ, chất tạo màu tự nhiên (curcumin (100(i))).
CÁC GÓI GIA VỊ - Đường, muối, dầu thực vật (dầu cọ, chất chống oxy hoá (BHA (320), BHT (321))), chất điều vị (mononatri glutamat (621), dinatri 5'-inosinat (631), dinatri 5'-guanylat (627)), các gia vị, chất điều chỉnh độ acid (acid citric (330)), bột tôm 2,83 g/kg, hành lá sấy, nước mắm, chất tạo màu tự nhiên (paprika oleoresin (160c), curcumin (100(i)), chất tạo ngọt tổng hợp (aspartam (951)).", ' Cho vắt mì, gói súp và gói dầu vào tô. Chế nước sôi vào khoảng 400 ml, đậy nắp lại và chờ 3 phút. Trộn đều và dùng được ngay.', '75g ', 'nơi thoáng mát', '', 'Không dành cho trẻ dưới 1 tuổi', '', '6 tháng', 1],
            ['Gói Mì Hảo Hảo tôm chua cay 75g ', '4', '14', 'mi-hao-hao-tom-chua-cay-goi-75g_300x300.jpg', " VẮT MÌ - Bột mì (bổ sung vi chất (kẽm, sắt)), dầu thực vật (dầu cọ, chất chống oxy hoá (BHA (320), BHT (321))), tinh bột, muối, đường, nước mắm, chất điều vị (mononatri glutamat (621)), chất ổn định (pentanatri triphosphat (451(i), kali carbonat (501(i))), chất điều chỉnh độ acid (natri carbonat (500(i))), bột nghệ, chất tạo màu tự nhiên (curcumin (100(i))).
CÁC GÓI GIA VỊ - Đường, muối, dầu thực vật (dầu cọ, chất chống oxy hoá (BHA (320), BHT (321))), chất điều vị (mononatri glutamat (621), dinatri 5'-inosinat (631), dinatri 5'-guanylat (627)), các gia vị, chất điều chỉnh độ acid (acid citric (330)), bột tôm 2,83 g/kg, hành lá sấy, nước mắm, chất tạo màu tự nhiên (paprika oleoresin (160c), curcumin (100(i)), chất tạo ngọt tổng hợp (aspartam (951)).", ' Cho vắt mì, gói súp và gói dầu vào tô. Chế nước sôi vào khoảng 400 ml, đậy nắp lại và chờ 3 phút. Trộn đều và dùng được ngay.', '75g ', 'nơi thoáng mát', '', 'Không dành cho trẻ dưới 1 tuổi', '', '6 tháng', 1],
            ['Gói Mì Hảo Hảo sa tế hành 75g ', '4', '14', 'mi-hao-hao-sa-te-hanh_300x300.jpg', " VẮT MÌ - Bột mì (bổ sung vi chất (kẽm, sắt)), dầu thực vật (dầu cọ, chất chống oxy hoá (BHA (320), BHT (321))), tinh bột, muối, đường, nước mắm, chất điều vị (mononatri glutamat (621)), chất ổn định (pentanatri triphosphat (451(i), kali carbonat (501(i))), chất điều chỉnh độ acid (natri carbonat (500(i))), bột nghệ, chất tạo màu tự nhiên (curcumin (100(i))).
CÁC GÓI GIA VỊ - Đường, muối, dầu thực vật (dầu cọ, chất chống oxy hoá (BHA (320), BHT (321))), chất điều vị (mononatri glutamat (621), dinatri 5'-inosinat (631), dinatri 5'-guanylat (627)), các gia vị, chất điều chỉnh độ acid (acid citric (330)), bột tôm 2,83 g/kg, hành lá sấy, nước mắm, chất tạo màu tự nhiên (paprika oleoresin (160c), curcumin (100(i)), chất tạo ngọt tổng hợp (aspartam (951)).", ' Cho vắt mì, gói súp và gói dầu vào tô. Chế nước sôi vào khoảng 400 ml, đậy nắp lại và chờ 3 phút. Trộn đều và dùng được ngay.', '75g ', 'nơi thoáng mát', '', 'Không dành cho trẻ dưới 1 tuổi', '', '6 tháng', 1],
            ['Thùng Mì Hảo Hảo sa tế hành 75g ', '4', '14', 'thung-mi-hao-hao-sa-te-hanh_300x300.jpg', " VẮT MÌ - Bột mì (bổ sung vi chất (kẽm, sắt)), dầu thực vật (dầu cọ, chất chống oxy hoá (BHA (320), BHT (321))), tinh bột, muối, đường, nước mắm, chất điều vị (mononatri glutamat (621)), chất ổn định (pentanatri triphosphat (451(i), kali carbonat (501(i))), chất điều chỉnh độ acid (natri carbonat (500(i))), bột nghệ, chất tạo màu tự nhiên (curcumin (100(i))).
CÁC GÓI GIA VỊ - Đường, muối, dầu thực vật (dầu cọ, chất chống oxy hoá (BHA (320), BHT (321))), chất điều vị (mononatri glutamat (621), dinatri 5'-inosinat (631), dinatri 5'-guanylat (627)), các gia vị, chất điều chỉnh độ acid (acid citric (330)), bột tôm 2,83 g/kg, hành lá sấy, nước mắm, chất tạo màu tự nhiên (paprika oleoresin (160c), curcumin (100(i)), chất tạo ngọt tổng hợp (aspartam (951)).", ' Cho vắt mì, gói súp và gói dầu vào tô. Chế nước sôi vào khoảng 400 ml, đậy nắp lại và chờ 3 phút. Trộn đều và dùng được ngay.', '75g ', 'nơi thoáng mát', '', 'Không dành cho trẻ dưới 1 tuổi', '', '6 tháng', 1],
            [' Thùng mì 3 Miền tôm chua cay 65g ', '4', '15', 'thung-mi-3-mien-tom-chua-cay-65g_300x300.jpg', " VẮT MÌ - Bột mì (75,0%), shortening, phẩm màu (curcumin (E100(i)).GÓI GIA VỊ - Bột tôm (30 g/kg), dầu cọ, muối, đường, bột tỏi, bột ớt, hành lá sấy, chất điều chỉnh độ acid (citric acid (E330)), chất điều vị (monosodium L-glutamate (E621), disodium 5'-inosinate (E631), disodium 5'-guanylate (E627)).", ' Cho vắt mì, gói súp và gói dầu vào tô. Chế nước sôi vào khoảng 400 ml, đậy nắp lại và chờ 3 phút. Trộn đều và dùng được ngay.', '65g ', 'nơi thoáng mát', '', 'Không dành cho trẻ dưới 1 tuổi', '', '6 tháng', 1],
            ['Gói mì 3 Miền tôm chua cay 65g ', '4', '15', 'thung-mi-3-mien-tom-chua-cay-65g-2.jpg', " VẮT MÌ - Bột mì (75,0%), shortening, phẩm màu (curcumin (E100(i)).GÓI GIA VỊ - Bột tôm (30 g/kg), dầu cọ, muối, đường, bột tỏi, bột ớt, hành lá sấy, chất điều chỉnh độ acid (citric acid (E330)), chất điều vị (monosodium L-glutamate (E621), disodium 5'-inosinate (E631), disodium 5'-guanylate (E627)).", ' Cho vắt mì, gói súp và gói dầu vào tô. Chế nước sôi vào khoảng 400 ml, đậy nắp lại và chờ 3 phút. Trộn đều và dùng được ngay.', '65g ', 'nơi thoáng mát', '', 'Không dành cho trẻ dưới 1 tuổi', '', '6 tháng', 1],

        ];
        for ($i = 0; $i < count($dsSanPham); $i++) {
            array_push($list, [
                'sp_ten' => $dsSanPham[$i][0],
                'lsp_ma' => $dsSanPham[$i][1],
                'nsx_ma' => $dsSanPham[$i][2],
                'sp_anhDaiDien' => $dsSanPham[$i][3],
                'sp_thanhPhan' => $dsSanPham[$i][4],
                'sp_cachDung' => $dsSanPham[$i][5],
                'sp_khoiLuong' => $dsSanPham[$i][6],
                'sp_baoQuan' => $dsSanPham[$i][7],
                'sp_doiTuongDung' => $dsSanPham[$i][8],
                'sp_ghiChu' => $dsSanPham[$i][9],
                'sp_moTaNgan' => $dsSanPham[$i][10],
                'sp_hanDung' => $dsSanPham[$i][11],
                'sp_trangThai' => $dsSanPham[$i][12],
                'created_at' => $date
            ]);
        }
        DB::table('sanpham')->insert($list);
    }
}
